let PI = Math.PI
console.log(PI)
console.log(Math.round(PI))
console.log(Math.floor(PI))
console.log(Math.ceil(PI))
console.log(Math.abs(8))
console.log(Math.sqrt(25))
console.log(Math.pow(10,3))
console.log(Math.max(2,5,28,8,7,4))
console.log(Math.min(2,5,28,8,7,4,-5,6))
console.log(Math.log(2))
console.log(Math.log(10))
Math.sin(0)
Math.sin(60)
Math.cos(30)

